### ISSUE TITLE
Homebridge service restarts

### ISSUE THREAD

**Issue by HomebridgeX** [cbrandlehner/homebridge-luxtronik2#150]
Hello, 

I have the problem that when I open the "Home" app, then I get the following error message in the Homebridge and the Homebridge service restarts:

RangeError: The value of "offset" is out of range. It must be >= 0 and <= 0. Received 8
    at new NodeError (node:internal/errors:399:5)
    at boundsError (node:internal/buffer:88:9)
    at Buffer.readUInt32BE (node:internal/buffer:311:5)
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-luxtronik2/index.js:144:22)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:293:11)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
Homebridge service restarts

Thanks for the help

**Comment by cbrandlehner** [comment]
@HomebridgeX please enable debug on homebridge and provide a full log.

**Comment by cbrandlehner** [comment]
I reviewed that code section, made a small change and added some debug.
Please use version 1.0.2 and make sure to enable debug mode and provide a FULL log.

**Comment by HomebridgeX** [comment]
Here is the log file: https://1drv.ms/f/s!Ar6tzOqZoAnFj5MjxhH5eu30F1jaPQ?e=H1oS0l

**Comment by HomebridgeX** [comment]
If anything else is needed, feel free to contact me.

**Comment by cbrandlehner** [comment]
Hi @HomebridgeX , to clarify my request: When asking for a full log, I was requesting a log from the START of Homebridge up to the occurance of the problem. The file provided by you is so large because it contains all the history of previous starts.

The log file also contains log from other plugins. Did you know that you can temporarily disable plugins?

![Bildschirmfoto 2023-04-19 um 09 15 07](https://user-images.githubusercontent.com/10800971/232997065-115f96bf-1692-40e3-8906-669fa3bee043.png)

Regarding Debug Mode. There are two differend debug modes. Please enable Homebridge Debugging in the Homebridge-Settings.
![Bildschirmfoto 2023-04-19 um 09 21 19](https://user-images.githubusercontent.com/10800971/232999496-d09fdcc8-6a19-4672-9702-fba63a751545.png)

My advise is to use all plugins in child bridges. In Tools - Bridge Settings you can enable these child bridge feature. When using child bridges, a crashing plugin will not cause a restart of homebridge including all other plugins.
![Bildschirmfoto 2023-04-19 um 09 28 17](https://user-images.githubusercontent.com/10800971/233001058-1df5e6f1-b5ce-4b71-8380-61e53cb5ebac.png)


Please explain the problem situation:
- Is this a new installation?
- - Yes, it never worked before
- - No, it worked with an older version of the plugin. Which one?

**Comment by cbrandlehner** [comment]
Are you sure it worked with version 1.0.1?

Please re-test by installing the old version. You can do so by using Tools - Install Alternate Version.

If the old version works, I can see what changed in the code and causes the problem. Strange enough, the problem does not reproduce in my environment.

**Comment by HomebridgeX** [comment]
Sorry, misunderstanding, I already had the problem with 1.0.1

**Comment by HomebridgeX** [comment]
One more piece of additional info:

I retrieve 5 values:

Temperature_TVL
Temperature_TRL
Set_value_TRL_HZ
Temperature_TBW
Temperature_TA

**Comment by HomebridgeX** [comment]
Should I run the Luxtronik2 plugin in child bridges mode for testing? 
Would it be possible to not have to create a separate bridge for each sensor, but a bridge for the complete plugin?

**Comment by cbrandlehner** [comment]
For testing it is not necessary to use child bridges.
If you use child bridges, you can do so per sensor.

The problem is quite weird. The code in question is this here:
```
const {Buffer} = require('node:buffer');
      const buf = Buffer.alloc(data.length);
			buf.write(data, 'binary');
			/* luxtronik must confirm command */
			const confirm = buf.readUInt32BE(0);
			/* is 0 if data is unchanged since last request */
			// never used later in code ?? var change = buf.readUInt32BE(4);
			/* number of values */
			// const count = buf.readUInt32BE(8); // moved that code down into the else clause section.
			if (confirm === 3004) {
        that.log.debug('Luxtronik2 confirmed command.');
        const count = buf.readUInt32BE(8);
        if (data.length === (count * 4) + 12) {
				  let pos = 12;
				  const calculated = new Int32Array(count);
				  for (let i = 0; i < count; i++) {
				  	calculated[i] = buf.readInt32BE(pos);
				  	pos += 4;
				  }

          that.log.debug('Data received: %s', calculated);
```

The code is preparing to receive binary data. The Buffer is reserving a buffer to store the date (data.lenght).
Next, the code sends a request to luxtronix to ask for data.
Only if luctronix confirms that request, by sending code 3004, the code continues.

The function readUInt32BE(0) reads the first 32-bit unsigned integer from the Buffer object, skipping 0 bytes.

The code uses the same function later to read data from position 9 by using readUInt32BE(8), skipping the first 8 bytes.
This is where the problem occurs.

For whatever reason, in your environment the data returned by luxtronik is not in the expected format. It seems to return only one byte.

**Comment by HomebridgeX** [comment]
This is really strange, unfortunately I do not know what else I could test.
The temperatures are displayed correctly, unless it just restarts the service.
I love the extension and hope that there will be a solution to the problem.

**Comment by HomebridgeX** [comment]
With child bridges, unfortunately, the error also occurs.
Could it make sense that I contact Alpha Innotec?
Maybe it is a bug in the current firmware?

**Comment by cbrandlehner** [comment]
@HomebridgeX took some time but I figured out how to check if the buffer received is large enough. Please retry with updated version.
